SELECT * FROM buenasalud.empleados;
CREATE PROCEDURE NUMEMP_DEPT  SMALLINT
AS SELECT COUNT(*) AS [NUM EMPLEADOS], DEPT_NO
FROM EMP
WHERE DEPT_NO = @NDEP
GROUP BY DEPT_NO

EXEC NUMEMP_DEPT 30

SELECT id, oficio,apellido, FECHA_ALT from empleados where id =99%4


select count(1) FROM empleados;
CREATE PROCEDURE SALARIO_OFICIO @APELLIDO NVARCHAR(20) AS
SELECT OFICIO, SALARIO, COMISION FROM EMP WHERE APELLIDO = @PAPELLIDO

EXEC SALARIO_OFICIO 'GARCIA'

